[package]

name = "staticfile"
version = "0.0.3"
authors = ["Zach Pomerantz <zmp@umich.edu>"]
description = "Static file serving for Iron."
repository = "https://github.com/iron/staticfile"
license = "MIT"

[features]
cache = ["filetime"]

[dependencies]
iron = "0.1"
mount = "0"
time = "0.1"
log = "0.3"

[dependencies.filetime]
version = "0.1"
optional = true

[dev-dependencies]
iron-test = "*"
hyper = "0.6"
