[package]

name = "staticfile"
version = "0.0.4"
authors = ["Zach Pomerantz <zmp@umich.edu>"]
description = "Static file serving for Iron."
repository = "https://github.com/iron/staticfile"
license = "MIT"

[dependencies]
iron = "*"
mount = "*"
time = "*"
router = "*"
log = "*"

[dev-dependencies]
iron-test = "*"
hyper = "*"
