[package]

name = "staticfile"
version = "0.0.3"
authors = ["Zach Pomerantz <zmp@umich.edu>"]
description = "Static file serving for Iron."
repository = "https://github.com/iron/staticfile"
license = "MIT"

[features]
cache = ["filetime"]

[dependencies]
iron = "*"
mount = "*"
time = "*"
router = "*"
log = "*"

[dependencies.filetime]
version = "*"
optional = true

[dev-dependencies]
iron-test = "*"
hyper = "*"
