[package]

name = "static"
version = "0.0.3"
authors = ["Zach Pomerantz <zmp@umich.edu>"]
description = "Static file serving for Iron."
repository = "https://github.com/iron/static"
license = "MIT"

[dependencies]
iron = "*"
mount = "*"
time = "*"
router = "*"
iron-test = "*"
log = "*"

