[package]

name = "staticfile"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>", "Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Static file serving for Iron."
repository = "https://github.com/iron/staticfile"
license = "MIT"
keywords = ["iron", "web", "http", "file"]

[features]
cache = ["filetime"]

[dependencies]
iron = "0.3"
mount = "0.1"
time = "0.1"
log = "0.3"
url = "0.5"

[dependencies.filetime]
version = "0.1"
optional = true

[dev-dependencies]
iron-test = "0.3"
hyper = "0.8"
router = ">=0.1.1"
